### PR TITLE
fix: lure issue

### LINKED ISSUE #26: Possible lure issue
https://github.com/RealDeviceMap/RealDeviceMap/pull/410/files

spotted by fabio in his swift conversion

### PR DESCRIPTION
**Pull request by Fabio1988**
resolves #26

### CODE REVIEW

File: decoder/pokestop.go [hunk 1]
```diff
@@ -193,20 +193,26 @@ func (stop *Pokestop) updatePokestopFromFort(fortData *pogo.PokemonFortProto, ce
...
 		lureId := int16(fortData.ActiveFortModifier[0])
 		if lureId >= 501 && lureId <= 510 {
 			lureEnd := lastModifiedTimestamp + LureTime
+			oldLureEnd := stop.LureExpireTimestamp.ValueOrZero()
 			if stop.LureId != lureId {
 				stop.LureExpireTimestamp = null.IntFrom(lureEnd)
 				stop.LureId = lureId
 			} else {
 				now := time.Now().Unix()
-				if now > (lureEnd + 30) { // wait some time after lure end before a restart in case of timing issue
```
Comment (Fabio1988) [inline decoder/pokestop.go:208]: if the same lure is deployed again (normal -> normal) the lureEnd (lastModfified + 1800) variable is always in the future. therefore we never updated the lure expire timestamp :confused:

Comment (jfberry) [reply decoder/pokestop.go:208]: What doughnut wrote that code! Looks good to me, merge upon successful test

**Comment by TiMXL73** [comment]
Commit applied over 2 hours ago and checking regularly every since. No issues to report and Lures are now the same in Golbat and RDM. Thank you!
