### PR TITLE
Truncate route description

### LINKED ISSUE #204: route descriptions too long to fit into DB column
I'm seeing a number of these:

```
ERRO 2024-01-13 14:26:18 Failed to decode route insert route error: Error 1406 (22001): Data too long for column 'description' at row 1
```

I tried to truncate... which should truncate on character boundary, not octet boundary... but, I've got this now, lol.

```
WARN 2024-01-13 16:53:47 truncating description for route id 'yokohamaWCS3kml'. Orig description: 赤レンガ倉庫の日本最古の荷役用エレベーター前と、桜木町駅前のポケふた(※)「ピカチュウ」を結ぶルート。新港中央広場を通り抜け、ヨコハマエアキャビンを眺めながら汽車道を歩こう。

(WCSとは、ポケモンのゲーム部門・カードゲーム部門・『ポケモン GO』部門・『ポケモンユナイト』部門の4部門の世界一を決める大会のこと。毎年世界中から、各地域や国の激戦を勝ち抜いたプレイヤーが参加し、世界チャンピオンを巡って熱いバトルが繰り広げられます。)

※ポケモンマンホール「ポケふた」とは、ポケモンの絵が描かれたマンホール蓋のこと。1枚1枚がすべてオリジナルデザインで、世界にひとつだけのマンホール蓋です。
ERRO 2024-01-13 16:53:47 Failed to decode route insert route error: Error 1366 (22007): Incorrect string value: '\xE3' for column `golbat`.`route`.`description` at row 1
```

### PR DESCRIPTION
**Pull request by comstud**
I'm seeing a number of these:

```
ERRO 2024-01-13 14:26:18 Failed to decode route insert route error: Error 1406 (22001): Data too long for column 'description' at row 1
```

Rather than increase the VARCHAR(255) at this time, I've chosen to just truncate the description and log info about it. Truncating unicode correctly is a bit of fun.

Fixes #204

### CODE REVIEW

**Comment by comstud** [comment]
I've tested this and this fixes the DB fails I was seeing.

File: decoder/routes.go [hunk 1]
```diff
@@ -94,6 +95,32 @@ func saveRouteRecord(db db.DbDetails, route *Route) error {
...
+		defer func(oldDescr string) {
+			route.Description = oldDescr
+		}(route.Description)
+
+		log.Warnf("truncating description for route id '%s'. Orig description: %s",
+			route.Id,
+			route.Description,
+		)
+
+		// this splits on rune boundaries instead of byte boundaries. only
```
Comment (jfberry) [inline decoder/routes.go:108]: r := []rune(text)
   trunc := r[:width]

?

Comment (comstud) [reply decoder/routes.go:108]: yeah, I didn't do that because it causes an allocation, supposedly. But I guess when stop to think about it, who cares, in this spot. I'll change it.

**Comment by comstud** [comment]
My len() check was also wrong. This new version has been tested now also.

**Comment by comstud** [comment]
I swear I left a question here to others and myself.... but I don't see it. I probably left it on another PR by accident ha, but:

I'm wondering if this is not the correct spot to do this. I was trying to preserve the original description in here with the defer, but I think maybe this is just kinda dumb.

Maybe Description should be truncated when *Route is initially formed, and just let it be truncated ?

**Comment by comstud** [comment]
Yeah, I think so. I've updated this.

**Review by Fabio1988 — APPROVED** [review]

**Review by Fabio1988 — APPROVED** [review]
